theme: jekyll-theme-minimal
lang: ru
title: faq x81
description: "жирный faq по маркообразным в 81 кузове"
opengraph_type: "article"
url: "https://daks01.github.io/FAQx81/"
image: "/assets/img/logo.png"
plugins:
  - jekyll-toc
toc: true