theme: jekyll-theme-minimal
lang: ru
title: 'faq*x81'
description: 'жирный faq по маркообразным в 81 кузове'
opengraph_type: 'article'
url: 'https://daks01.github.io/FAQx81/faq'
logo: '/assets/images/logo.png'
image : '/assets/images/logo.png'
toc: true
search: true
search_full_content: false
search_provider: lunr
plugins:
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-lunr-js-search